---
galaxy_info:
  author: Afzal
  description: Configures Nginx as a load balancer with basic auth
  company: Personal Project
  license: MIT
  min_ansible_version: "2.9"
  galaxy_tags: []
dependencies: []
